# Generated by Django 2.0.7 on 2018-07-20 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('alcobas', models.CharField(help_text='Breve despcripcion de las alcobas', max_length=100)),
                ('garaje', models.BooleanField(default=False)),
                ('terraza', models.BooleanField(default=False)),
                ('comedor', models.BooleanField(default=False)),
                ('cocina', models.BooleanField(default=False)),
                ('baño', models.CharField(help_text='Breve despcripcion de los baños', max_length=100)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.AddField(
            model_name='edificio',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorasApp.Imagenes'),
        ),
        migrations.AddField(
            model_name='constructora',
            name='edificios',
            field=models.ManyToManyField(to='constructorasApp.Edificio'),
        ),
        migrations.AddField(
            model_name='constructora',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorasApp.Imagenes'),
        ),
    ]
