# Generated by Django 2.0.7 on 2018-07-20 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructorasApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcobas', models.CharField(help_text='Breve despcripcion de las alcobas', max_length=100)),
                ('garaje', models.BooleanField(default=False)),
                ('terraza', models.BooleanField(default=False)),
                ('comedor', models.BooleanField(default=False)),
                ('cocina', models.BooleanField(default=False)),
                ('baño', models.CharField(help_text='Breve despcripcion de los baños', max_length=100)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='alcobas',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='baño',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='cocina',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='comedor',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='garaje',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='terraza',
        ),
        migrations.AddField(
            model_name='imagenes',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartamento',
            name='imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorasApp.Imagenes'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='apartamentos',
            field=models.ManyToManyField(to='constructorasApp.Apartamento'),
        ),
    ]
