# Generated by Django 2.0.7 on 2018-07-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructorasApp', '0002_auto_20180719_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='descripcion_general',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
