# Generated by Django 2.0.7 on 2018-07-20 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructorasApp', '0004_auto_20180719_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgApartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='apartamento',
            name='imagen',
        ),
        migrations.AddField(
            model_name='imgapartamento',
            name='id_apartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorasApp.Apartamento'),
        ),
        migrations.AddField(
            model_name='imgapartamento',
            name='id_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructorasApp.Imagenes'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='imagen',
            field=models.ManyToManyField(through='constructorasApp.ImgApartamento', to='constructorasApp.Imagenes'),
        ),
    ]
