# Generated by Django 2.0.7 on 2018-07-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructorasApp', '0005_auto_20180719_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructora',
            name='imagen',
            field=models.ImageField(upload_to='fotosConstructoras/'),
        ),
    ]
