# Generated by Django 2.0.7 on 2018-07-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructorasApp', '0008_edificio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='descripcion',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
