# Generated by Django 2.0.7 on 2018-09-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructorasApp', '0010_auto_20180723_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartamento',
            name='nombre',
            field=models.CharField(default=1, help_text='Ingresar un identificador para el apartamento - Nombre + Edificio al que pertenece', max_length=100),
            preserve_default=False,
        ),
    ]
