# Generated by Django 2.1.3 on 2018-11-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructorasApp', '0011_apartamento_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructora',
            name='edificios',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='apartamentos',
        ),
        migrations.AddField(
            model_name='apartamento',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructorasApp.Edificio'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='constructora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructorasApp.Constructora'),
        ),
    ]
